version: "3"

services:
  bot:
    image: ghcr.io/alfirovich/support-bot-shm/bot:latest
    container_name: support-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    container_name: support-redis
    restart: always
    env_file:
      - .env
    volumes:
      - ./redis/data/:/data
    networks:
      - network

networks:
  network: